services:
  - type: web
    name: optiforce-app
    env: python
    buildCommand: |
      export CARGO_HOME=/tmp/cargo
      export RUSTUP_HOME=/tmp/rustup
      export PATH="$CARGO_HOME/bin:$PATH"

      curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain stable
      source $CARGO_HOME/env

      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn optiforce_app:app
    envVars:
      - key: CARGO_HOME
        value: /tmp/cargo
      - key: RUSTUP_HOME
        value: /tmp/rustup
